prd-sam PRD NONE
prd-samdev PRD NONE
par-sam PAR NONE
frf-sam FRF NONE
SAM SYD NONE
iad-sam IAD NONE
dfw-sam DFW NONE
ukb-sam UKB NONE
SAM CDU NONE
phx-sam PHX NONE
SAM YUL NONE
wax-sam WAX NONE
chx-sam CHX NONE
ord-sam ORD NONE
hnd-sam HND NONE
SAM YHU NONE
