prd-sam PRD NONE
prd-samdev PRD NONE
par-sam PAR NONE
hnd-sam HND NONE
SAM SYD NONE
iad-sam IAD NONE
dfw-sam DFW NONE
ukb-sam UKB NONE
SAM CDU NONE
phx-sam PHX NONE
SAM YUL NONE
ord-sam ORD NONE
SAM YHU NONE
frf-sam FRF NONE
