prd-sam PRD NONE
prd-samdev PRD NONE
par-sam PAR NONE
hnd-sam HND NONE
SAM SYD NONE
dfw-sam DFW NONE
wax-sam WAX NONE
SAM CDU NONE
phx-sam PHX NONE
SAM YUL NONE
iad-sam IAD NONE
chx-sam CHX NONE
ord-sam ORD NONE
frf-sam FRF NONE
ukb-sam UKB NONE
SAM YHU NONE
